services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"
      - "50000:50000"
    environment:
      JENKINS_OPTS: --prefix=/jenkins
    volumes:
      - .jenkins:/var/jenkins_home
    networks:
      - mynetwork

networks:
  mynetwork:
    external: true
