# docker-compose-backend.yml
version: "3"
services:
  backend1:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    depends_on:
      - resource_db
  backend2:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    depends_on:
      - resource_db
