# docker-compose-resource.yml
services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - mynetwork

networks:
  mynetwork:
    external: true
