services:
  front_dt:
    container_name: front_dt
    build:
      context: ./front_dt
    ports:
      - "5173:80"
    volumes:
      - /usr/share/nginx/html
    networks:
      - mynetwork

networks:
  mynetwork:
    external: true
