x-environments: &default
  env_file: .env # 기본 환경 파일을 지정합니다.

services:

  back_dt1:
    container_name: back_dt1
    build:
      context: ./back_dt/
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    <<: *default
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - mynetwork

  back_dt2:
    container_name: back_dt2
    build:
      context: ./back_dt/
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    <<: *default
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - mynetwork

  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    <<: *default
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mynetwork
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysqladmin ping -h localhost -u${MYSQL_ROOT_USER} -p${MYSQL_ROOT_PASSWORD}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data:
    driver: local
    driver_opts:
      type: none
      device: ./back_dt/mysql_data
      o: bind

networks:
  mynetwork:
    external: true
